kind: Service
apiVersion: v1
metadata:
  name: backendservice
  namespace: kube-system
spec:
  selector:
    app: backendDeployment
  ports:
  - name: apache
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30800
  - name: phpmyadmin
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30808

  type: NodePort

