apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: backendDeployment
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: backendDeployment
    spec:
      containers:
      - name: apache
        image: 037290061496.dkr.ecr.eu-west-1.amazonaws.com/docker-php-symfony-angular_apache:v11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80 
        resources:
          requests:
            cpu: 200m
      - name: mysql
        image: mysql
        ports:
        -  containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ${MYSQL_ROOT_PASSWORD}
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        - name: MYSQL_USER
          value: ${MYSQL_USER}
        - name: MYSQL_PASSWORD
          value: ${MYSQL_PASSWORD}
        resources:
          requests:
            cpu: 200m 
      - name: php
        image: 037290061496.dkr.ecr.eu-west-1.amazonaws.com/docker-php-symfony-angular_php:v11
        imagePullPolicy: IfNotPresent
        env:
        - name: maildev_host
          value: sf4_maildev
        resources:
          requests:
            cpu: 200m
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        -  containerPort: 8080
        env:
        - name: PMA_HOST
          value: mysql
        resources:
          requests:
            cpu: 200m
      - name: maildev  
        image: djfarrelly/maildev
        ports:
        -  containerPort: 8001
        resources:
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: my-docker-credentials
